version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - ${HOME}/.ssh:/home/vscode/.ssh:ro
      - node_modules:/workspace/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://devuser:devpass@postgres:5432/devdb
      - REDIS_URL=redis://redis:6379
      - MONGODB_URI=mongodb://mongodb:27017/devdb
    depends_on:
      - postgres
      - redis
      - mongodb
    networks:
      - dev-network
    ports:
      - "3000:3000"
      - "3001:3001"
      - "9229:9229" # Node.js debugging
    command: sleep infinity

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
      - POSTGRES_DB=devdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7
    environment:
      - MONGO_INITDB_DATABASE=devdb
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - dev-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Optional: Adminer for database management
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - dev-network
    depends_on:
      - postgres
      - mongodb
    profiles:
      - tools

  # Optional: RedisInsight for Redis management
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - redisinsight-data:/db
    networks:
      - dev-network
    profiles:
      - tools

volumes:
  postgres-data:
  mongo-data:
  redis-data:
  redisinsight-data:
  node_modules:

networks:
  dev-network:
    driver: bridge